### PR TITLE
Remove uglify

### PR DESCRIPTION
**Pull request by amowu**
修正 bfred-it/object-fit-images 在經過兩次 uglify 的情況下，部分瀏覽器 object-fit 功能失效問題。

### CODE REVIEW

**Comment by miterfrants** [comment]
checked OK

**Comment by fregante** [comment]
The non-minified version is now available in v3

https://github.com/bfred-it/object-fit-images/blob/master/dist/ofi.js

**Comment by fregante** [comment]
Also you should probably update to Uglify 2.7+ to avoid the issue you were having: https://github.com/bfred-it/object-fit-images/issues/37#issuecomment-255364967

**Comment by amowu** [comment]
@bfred-it Thanks!

**Pull request merged**
